### ISSUE TITLE
android sample example giving console errors (WebGL1 blacklisted)

### ISSUE THREAD

**Issue by omurbekjk** [2gis/MapGL-Android#2] opened 2019-10-21 02:48 UTC
```
E/chromium: [ERROR:context_group.cc(136)] ContextResult::kFatalFailure: WebGL1 blacklisted
D/EGL_emulation: eglMakeCurrent: 0xcddb7c40: ver 2 0 (tinfo 0xcb3a5150)
E/chromium: [ERROR:context_group.cc(136)] ContextResult::kFatalFailure: WebGL1 blacklisted
I/chromium: [INFO:CONSOLE(16)] "Uncaught TypeError: Cannot read property 'getExtension' of null", source: https://mapgl.2gis.com/api/js (16)
```

**Comment by lagner** [comment] 2019-10-22 04:05
Hi Omurbek.
Thank you for opening an issue.
Unfortunately there is not enougth information to sort it out. Can you provide more info about device you use and Android OS version.
If you use android emulator be sure that its latest release.

**Comment by omurbekjk** [comment] 2019-10-22 04:17
@lagner Thanks for your response. 
I was able to run it with correct API key.
How can I change center of a map when location changes?
Should I call `setup` method every time when location changes?

```
        mapFragment.mapReadyCallback = this::onDGisMapReady
        mapFragment.setup(
            apiKey = "api key",
            center = LonLat(55.291231, 25.227135),
            zoom = 16.0
        )
```

**Comment by lagner** [comment] 2019-10-22 07:19
*setup* should be called only once to initialize map.
To change map position you can set center property of Map object
```kotlin
private fun onDGisMapReady(map: DGisMap?) {
    map?.center = LonLat(56.291231, 25.227135)
}
```

**Comment by omurbekjk** [comment] 2019-10-22 09:45
Problem still exists in emulator:
1. Android version: 8.1 (Oreo) - API 27
2. Latest available emulator version: 29.2.5-5950156 (Canary update channel)
3. Emulator version: 29.0.11-5598178
4. Emulator ADB serial number: emulator-5554

But it did work on actual android phone

**Comment by mikhail-timofeev-epam** [comment] 2020-06-09 19:07
It is still reproducible on a real device:
1. Android 5.1.1
2. Model Huawei M2-A01L
3. Processor Hisilicon Kirion 930

**Comment by lagner** [comment] 2020-06-11 08:29
Hi @mikhail-timofeev-epam and thank you for the feedback.

To work with WebGL we use system WebView under the hood. According to the documentation, Android 5.0(and above) has system WebView that does support WebGL. Therefore it looks like something wrong has been done by the manufacturer.
Unfortunately, I have no idea how we can fix it for your phone.  

Can you check if the phone supports WebGL using https://get.webgl.org/ or such?

**Comment by mikhail-timofeev-epam** [comment] 2020-06-15 11:07
I have checked it with https://get.webgl.org/ and have found this line in the logcat

```
06-15 15:05:24.920 17988-18526/ru.dublgis.dgismobile.sdktestapp E/chromium: [ERROR:context_group.cc(145)] ContextResult::kFatalFailure: WebGL1 blacklisted
```
As I googled it, there is some driver block in the Chromium WebView. They just block some video processors prohibit to use WebGL. But at the same time, If I open this link in Chrome, it works.

One interesting fact, I have tried to find Map which is working on my device, and it seems like leaflet map from the official site works. Is 2gis based on this map?  (https://leafletjs.com/)

**Comment by lagner** [comment] 2020-06-17 04:02
> They just block some video processors prohibit to use WebGL

It sounds true. Unfortunately, we can do nothing with it.

> Is 2gis based on this map?

No, we don't use the LeafletJs. As I see the library is not a 3D map but it is a raster one. It works because it does not need WebGL.
You can use our raster map in a WebView. Check the following link
https://api.2gis.ru/doc/maps/ru/quickstart/
Maybe it works better in your case.

**Comment by mikhail-timofeev-epam** [comment] 2020-06-19 06:50
It seems like an issue related to Mali-Txxx GPUs.
https://bugs.chromium.org/p/chromium/issues/detail?id=934823

**Comment by lagner** [comment] 2020-07-22 04:51
Yes. I think we found out what the problem is. Unfortunately, we can do nothing with the Google Chrome bug.
Close the issue.

**Closed as completed by lagner** 2020-07-22 04:51 UTC
